/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-5'
 */
export const projectModel = {
  languages: {
    default: {
      codename: 'default',
      name: 'Default project language',
    },
  },
  contentTypes: {
    article: {
      codename: 'article',
      name: 'Article',
      elements: {
        author: {
          codename: 'author',
          name: 'Author',
        },
        display_options: {
          codename: 'display_options',
          name: 'Display options',
        },
        next_steps: {
          codename: 'next_steps',
          name: 'What\'s next?',
        },
        content_insights: {
          codename: 'content_insights',
          name: 'Content insights',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
        platform: {
          codename: 'platform',
          name: 'Platform',
        },
        display_mode: {
          codename: 'display_mode',
          name: 'Choose how to display the article',
        },
        short_title: {
          codename: 'short_title',
          name: 'Short title',
        },
        visibility: {
          codename: 'visibility',
          name: 'Visibility',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        redirect_urls: {
          codename: 'redirect_urls',
          name: 'Redirect URLs',
        },
        introduction: {
          codename: 'introduction',
          name: 'Introduction',
        },
      },
    },
    author: {
      codename: 'author',
      name: 'Author',
      elements: {
        photo: {
          codename: 'photo',
          name: 'Photo',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
      },
    },
    call_to_action: {
      codename: 'call_to_action',
      name: 'Call to action',
      elements: {
        link__link_to_content_item: {
          codename: 'link__link_to_content_item',
          name: 'Link to content item',
        },
        text: {
          codename: 'text',
          name: 'Text',
        },
        action: {
          codename: 'action',
          name: 'Action',
        },
        link__link_to_web_url: {
          codename: 'link__link_to_web_url',
          name: 'Link to web URL',
        },
      },
    },
    callout: {
      codename: 'callout',
      name: 'Callout',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
        type: {
          codename: 'type',
          name: 'Type',
        },
      },
    },
    carousel: {
      codename: 'carousel',
      name: 'Carousel',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
      },
    },
    changelog: {
      codename: 'changelog',
      name: 'List of release notes',
      elements: {},
    },
    code_sample: {
      codename: 'code_sample',
      name: 'Code sample',
      elements: {
        code: {
          codename: 'code',
          name: 'Code',
        },
        programming_language: {
          codename: 'programming_language',
          name: 'Programming language',
        },
        platform: {
          codename: 'platform',
          name: 'Platform',
        },
      },
    },
    code_samples: {
      codename: 'code_samples',
      name: 'Code samples',
      elements: {
        code_samples: {
          codename: 'code_samples',
          name: 'Code samples',
        },
      },
    },
    content_chunk: {
      codename: 'content_chunk',
      name: 'Content chunk',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
        platform: {
          codename: 'platform',
          name: 'Platform',
        },
      },
    },
    drag_and_drop: {
      codename: 'drag_and_drop',
      name: 'Training Drag and Drop',
      elements: {
        adapt_component_title__title: {
          codename: 'adapt_component_title__title',
          name: 'Title',
        },
        adapt_progress_settings__adjust_progress_settings: {
          codename: 'adapt_progress_settings__adjust_progress_settings',
          name: 'Adjust progress settings',
        },
        drag_and_drop_items: {
          codename: 'drag_and_drop_items',
          name: 'Drop Areas',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        displayoptions__css_classes: {
          codename: 'displayoptions__css_classes',
          name: 'Training CSS class',
        },
        feedback___incorrect: {
          codename: 'feedback___incorrect',
          name: 'Incorrect answer feedback',
        },
        layout: {
          codename: 'layout',
          name: 'Layout',
        },
        feedback___correct: {
          codename: 'feedback___correct',
          name: 'Correct answer feedback',
        },
        displayoptions__layout: {
          codename: 'displayoptions__layout',
          name: 'Layout',
        },
      },
    },
    drag_and_drop_answer: {
      codename: 'drag_and_drop_answer',
      name: 'Training Drag and Drop - Drop Area',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        items: {
          codename: 'items',
          name: 'Drag Tiles',
        },
      },
    },
    drag_and_drop_items: {
      codename: 'drag_and_drop_items',
      name: 'Training Drag and Drop - Drag tile',
      elements: {
        image_description: {
          codename: 'image_description',
          name: 'Image description',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
      },
    },
    embedded_content: {
      codename: 'embedded_content',
      name: 'Embedded content',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        zoomable: {
          codename: 'zoomable',
          name: 'Zoomable',
        },
        caption: {
          codename: 'caption',
          name: 'Caption',
        },
        provider: {
          codename: 'provider',
          name: 'Provider',
        },
        caption_title: {
          codename: 'caption_title',
          name: 'Caption',
        },
        id: {
          codename: 'id',
          name: 'ID',
        },
        width: {
          codename: 'width',
          name: 'Width',
        },
      },
    },
    footer: {
      codename: 'footer',
      name: 'Footer',
      elements: {
        copyright: {
          codename: 'copyright',
          name: 'Copyright',
        },
        external_links: {
          codename: 'external_links',
          name: 'External links',
        },
      },
    },
    homepage: {
      codename: 'homepage',
      name: 'Home (portal root)',
      elements: {
        description: {
          codename: 'description',
          name: 'Meta description for SEO',
        },
        title: {
          codename: 'title',
          name: 'Portal title',
        },
        subpages: {
          codename: 'subpages',
          name: 'Subpages',
        },
        intro_note: {
          codename: 'intro_note',
          name: 'Short promo note',
        },
        support: {
          codename: 'support',
          name: 'Support content',
        },
        signposts: {
          codename: 'signposts',
          name: 'Signpost content',
        },
      },
    },
    image: {
      codename: 'image',
      name: 'Image',
      elements: {
        zoomable: {
          codename: 'zoomable',
          name: 'Zoomable',
        },
        notes: {
          codename: 'notes',
          name: 'Notes',
        },
        description: {
          codename: 'description',
          name: 'Caption',
        },
        image_width: {
          codename: 'image_width',
          name: 'Width',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
        layout: {
          codename: 'layout',
          name: 'Alignment',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
      },
    },
    multiplatform_article: {
      codename: 'multiplatform_article',
      name: 'Multiple-technology article',
      elements: {
        children: {
          codename: 'children',
          name: 'Articles',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
      },
    },
    navigation_item: {
      codename: 'navigation_item',
      name: 'Navigation item',
      elements: {
        subpages: {
          codename: 'subpages',
          name: 'Subpages',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
      },
    },
    navigation_link: {
      codename: 'navigation_link',
      name: 'Navigation link',
      elements: {
        url: {
          codename: 'url',
          name: 'URL',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    not_found: {
      codename: 'not_found',
      name: '404 Page not found',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    platform_option: {
      codename: 'platform_option',
      name: 'Technology option',
      elements: {
        url: {
          codename: 'url',
          name: 'URL',
        },
        icon: {
          codename: 'icon',
          name: 'Icon',
        },
        platform: {
          codename: 'platform',
          name: 'Platform',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    platform_picker: {
      codename: 'platform_picker',
      name: 'Technology picker',
      elements: {
        options: {
          codename: 'options',
          name: 'Options',
        },
      },
    },
    quote: {
      codename: 'quote',
      name: 'Quote',
      elements: {
        quote: {
          codename: 'quote',
          name: 'Quote',
        },
        author: {
          codename: 'author',
          name: 'Author',
        },
      },
    },
    redirect_rule: {
      codename: 'redirect_rule',
      name: 'Redirect rule',
      elements: {
        redirect_to: {
          codename: 'redirect_to',
          name: 'Redirect to',
        },
        redirect_from: {
          codename: 'redirect_from',
          name: 'Redirect from',
        },
        why_does_this_redirect_exist_: {
          codename: 'why_does_this_redirect_exist_',
          name: 'Why does this redirect exist?',
        },
      },
    },
    release_note: {
      codename: 'release_note',
      name: 'Release note',
      elements: {
        affected_services: {
          codename: 'affected_services',
          name: 'Affected services',
        },
        release_date: {
          codename: 'release_date',
          name: 'Release date',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        severity: {
          codename: 'severity',
          name: 'Severity',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    signpost: {
      codename: 'signpost',
      name: 'Signpost',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        items_to_show: {
          codename: 'items_to_show',
          name: 'Items to show',
        },
        type: {
          codename: 'type',
          name: 'Appearance',
        },
      },
    },
    signpost_item: {
      codename: 'signpost_item',
      name: 'Signpost item',
      elements: {
        link__link_to_content_item: {
          codename: 'link__link_to_content_item',
          name: 'Link to content item',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        link__link_to_web_url: {
          codename: 'link__link_to_web_url',
          name: 'Link to web URL',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
      },
    },
    term_definition: {
      codename: 'term_definition',
      name: 'Term definition',
      elements: {
        definition: {
          codename: 'definition',
          name: 'Definition',
        },
        term: {
          codename: 'term',
          name: 'Term',
        },
      },
    },
    terminology: {
      codename: 'terminology',
      name: 'List of term definitions',
      elements: {},
    },
    training_accordion: {
      codename: 'training_accordion',
      name: 'Training Accordion',
      elements: {
        adapt_component_title__title: {
          codename: 'adapt_component_title__title',
          name: 'Title',
        },
        adapt_component_instruction__instruction: {
          codename: 'adapt_component_instruction__instruction',
          name: 'Instructions for learners (deprecated)',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        adapt_progress_settings__adjust_progress_settings: {
          codename: 'adapt_progress_settings__adjust_progress_settings',
          name: 'Adjust progress settings',
        },
        force_completion_: {
          codename: 'force_completion_',
          name: 'Require completion',
        },
        displayoptions__css_classes: {
          codename: 'displayoptions__css_classes',
          name: 'Training CSS class',
        },
        accordion_items: {
          codename: 'accordion_items',
          name: 'Accordion items',
        },
        displayoptions__layout: {
          codename: 'displayoptions__layout',
          name: 'Layout',
        },
      },
    },
    training_accordion_item: {
      codename: 'training_accordion_item',
      name: 'Training Accordion item',
      elements: {
        content: {
          codename: 'content',
          name: 'Content',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        image_position: {
          codename: 'image_position',
          name: 'Image position',
        },
      },
    },
    training_answer: {
      codename: 'training_answer',
      name: 'Training Answer',
      elements: {
        incorrect_feedback: {
          codename: 'incorrect_feedback',
          name: 'Incorrect answer feedback',
        },
        answer: {
          codename: 'answer',
          name: 'Answer',
        },
        correct_answer: {
          codename: 'correct_answer',
          name: 'Is this a correct answer?',
        },
      },
    },
    training_block: {
      codename: 'training_block',
      name: 'Training Block',
      elements: {
        adapt_progress_settings__adjust_progress_settings: {
          codename: 'adapt_progress_settings__adjust_progress_settings',
          name: 'Adjust progress settings',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        body: {
          codename: 'body',
          name: 'Description',
        },
      },
    },
    training_course: {
      codename: 'training_course',
      name: 'Training Course',
      elements: {
        redirect_urls: {
          codename: 'redirect_urls',
          name: 'Redirect URLs',
        },
        persona: {
          codename: 'persona',
          name: 'Persona',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        next_in_path: {
          codename: 'next_in_path',
          name: 'Which course should learners take next?',
        },
        is_free: {
          codename: 'is_free',
          name: 'Offer course for free',
        },
        display_options: {
          codename: 'display_options',
          name: 'Display options',
        },
        training_course: {
          codename: 'training_course',
          name: 'Training course',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
        talentlms_course_id: {
          codename: 'talentlms_course_id',
          name: 'TalentLMS course ID for production',
        },
        introduction: {
          codename: 'introduction',
          name: 'Introduction',
        },
        thumbnail: {
          codename: 'thumbnail',
          name: 'Thumbnail',
        },
        duration: {
          codename: 'duration',
          name: 'Estimated course duration',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
      },
    },
    training_hot_graphic: {
      codename: 'training_hot_graphic',
      name: 'Training Hot Graphic',
      elements: {
        pins: {
          codename: 'pins',
          name: 'Pins',
        },
        adapt_component_title__title: {
          codename: 'adapt_component_title__title',
          name: 'Title',
        },
        adapt_progress_settings__adjust_progress_settings: {
          codename: 'adapt_progress_settings__adjust_progress_settings',
          name: 'Adjust progress settings',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        graphic: {
          codename: 'graphic',
          name: 'Graphic',
        },
        displayoptions__css_classes: {
          codename: 'displayoptions__css_classes',
          name: 'Training CSS class',
        },
        use_numbered_pins: {
          codename: 'use_numbered_pins',
          name: 'Use numbered pins',
        },
        displayoptions__layout: {
          codename: 'displayoptions__layout',
          name: 'Layout',
        },
      },
    },
    training_hot_graphic_pin: {
      codename: 'training_hot_graphic_pin',
      name: 'Training Hot Graphic Pins',
      elements: {
        top: {
          codename: 'top',
          name: 'Top',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        body: {
          codename: 'body',
          name: 'Body',
        },
        left: {
          codename: 'left',
          name: 'Left',
        },
        pin_selector: {
          codename: 'pin_selector',
          name: 'Pin selector',
        },
      },
    },
    training_narrative: {
      codename: 'training_narrative',
      name: 'Training Narrative',
      elements: {
        narrative_items: {
          codename: 'narrative_items',
          name: 'Narrative items',
        },
        adapt_component_title__title: {
          codename: 'adapt_component_title__title',
          name: 'Title',
        },
        adapt_component_instruction__instruction: {
          codename: 'adapt_component_instruction__instruction',
          name: 'Instructions for learners (deprecated)',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        force_completion_: {
          codename: 'force_completion_',
          name: 'Require completion',
        },
        adapt_progress_settings__adjust_progress_settings: {
          codename: 'adapt_progress_settings__adjust_progress_settings',
          name: 'Adjust progress settings',
        },
      },
    },
    training_narrative_item: {
      codename: 'training_narrative_item',
      name: 'Training Narrative item',
      elements: {
        body: {
          codename: 'body',
          name: 'Description',
        },
        code_sample: {
          codename: 'code_sample',
          name: 'Code sample',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
      },
    },
    training_page: {
      codename: 'training_page',
      name: 'Training Page',
      elements: {
        duration: {
          codename: 'duration',
          name: 'Lesson duration',
        },
        description: {
          codename: 'description',
          name: 'Lesson description',
        },
        call_to_action: {
          codename: 'call_to_action',
          name: 'Call to action',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
        course: {
          codename: 'course',
          name: 'Training Course',
        },
        image: {
          codename: 'image',
          name: 'Thumbnail',
        },
        title: {
          codename: 'title',
          name: 'Lesson title',
        },
        content: {
          codename: 'content',
          name: 'Lesson content',
        },
      },
    },
    training_question: {
      codename: 'training_question',
      name: 'Training Question',
      elements: {
        adapt_component_title__title: {
          codename: 'adapt_component_title__title',
          name: 'Title',
        },
        adapt_component_instruction__instruction: {
          codename: 'adapt_component_instruction__instruction',
          name: 'Instructions for learners (deprecated)',
        },
        adapt_progress_settings__adjust_progress_settings: {
          codename: 'adapt_progress_settings__adjust_progress_settings',
          name: 'Adjust progress settings',
        },
        feedback_title: {
          codename: 'feedback_title',
          name: 'Feedback title (deprecated)',
        },
        question: {
          codename: 'question',
          name: 'Question',
        },
        feedback_if_correct: {
          codename: 'feedback_if_correct',
          name: 'Correct answer feedback',
        },
        displayoptions__css_classes: {
          codename: 'displayoptions__css_classes',
          name: 'Training CSS class',
        },
        answers: {
          codename: 'answers',
          name: 'Answers',
        },
        feedback_if_partly_correct: {
          codename: 'feedback_if_partly_correct',
          name: 'Partly correct answer feedback',
        },
        feedback_if_incorrect: {
          codename: 'feedback_if_incorrect',
          name: 'Incorrect answer feedback',
        },
        displayoptions__layout: {
          codename: 'displayoptions__layout',
          name: 'Layout',
        },
      },
    },
    training_text: {
      codename: 'training_text',
      name: 'Training Text',
      elements: {
        adapt_component_title__title: {
          codename: 'adapt_component_title__title',
          name: 'Title',
        },
        adapt_component_instruction__instruction: {
          codename: 'adapt_component_instruction__instruction',
          name: 'Instructions for learners (deprecated)',
        },
        adapt_progress_settings__adjust_progress_settings: {
          codename: 'adapt_progress_settings__adjust_progress_settings',
          name: 'Adjust progress settings',
        },
        displayoptions__css_classes: {
          codename: 'displayoptions__css_classes',
          name: 'Training CSS class',
        },
        content: {
          codename: 'content',
          name: 'Content',
        },
        displayoptions__layout: {
          codename: 'displayoptions__layout',
          name: 'Layout',
        },
      },
    },
    training_unit: {
      codename: 'training_unit',
      name: 'Training Unit',
      elements: {
        score_to_pass: {
          codename: 'score_to_pass',
          name: 'Score to pass',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        answers_order: {
          codename: 'answers_order',
          name: 'Training Question – Order of answers',
        },
        pages: {
          codename: 'pages',
          name: 'Pages',
        },
        course_id: {
          codename: 'course_id',
          name: 'Data generator course ID',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        attempts_per_question: {
          codename: 'attempts_per_question',
          name: 'Training Question – Attempts per question',
        },
        course: {
          codename: 'course',
          name: 'Training Course',
        },
      },
    },
    training_video_v2: {
      codename: 'training_video_v2',
      name: 'Training Video',
      elements: {
        adapt_component_title__title: {
          codename: 'adapt_component_title__title',
          name: 'Title',
        },
        adapt_progress_settings__adjust_progress_settings: {
          codename: 'adapt_progress_settings__adjust_progress_settings',
          name: 'Adjust progress settings',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        displayoptions__css_classes: {
          codename: 'displayoptions__css_classes',
          name: 'Training CSS class',
        },
        video: {
          codename: 'video',
          name: 'Video',
        },
        displayoptions__layout: {
          codename: 'displayoptions__layout',
          name: 'Layout',
        },
      },
    },
    ui_messages: {
      codename: 'ui_messages',
      name: 'UI messages',
      elements: {
        video___replay: {
          codename: 'video___replay',
          name: 'Video - Replay',
        },
        search___placeholder: {
          codename: 'search___placeholder',
          name: 'Search - Placeholder',
        },
        feedback_form___yes_button: {
          codename: 'feedback_form___yes_button',
          name: 'Feedback form - Yes button',
        },
        form_field_validation___empty_field: {
          codename: 'form_field_validation___empty_field',
          name: 'Form field validation - empty field',
        },
        training___cta_revisit_course: {
          codename: 'training___cta_revisit_course',
          name: 'Training - CTA Revisit Course',
        },
        banner_for_dev_environment: {
          codename: 'banner_for_dev_environment',
          name: 'Banner for dev environment',
        },
        banner_for_preview_environment: {
          codename: 'banner_for_preview_environment',
          name: 'Banner for preview environment',
        },
        code_block___copy_code_button_active: {
          codename: 'code_block___copy_code_button_active',
          name: 'Code block - Copy code button active',
        },
        sign_in_error_text: {
          codename: 'sign_in_error_text',
          name: 'Sign in error text',
        },
        training___sign_in: {
          codename: 'training___sign_in',
          name: 'Training - CTA Sign In',
        },
        next_part_link_text: {
          codename: 'next_part_link_text',
          name: 'Article - Next part link text',
        },
        training___add_to_linkedin: {
          codename: 'training___add_to_linkedin',
          name: 'Training - Add to LinkedIn',
        },
        training___estimated_duration: {
          codename: 'training___estimated_duration',
          name: 'Training - Estimated Duration',
        },
        article___no_author: {
          codename: 'article___no_author',
          name: 'Article - No author',
        },
        training___cta_buy_course: {
          codename: 'training___cta_buy_course',
          name: 'Training - CTA Buy Course',
        },
        cookie_policy_bar: {
          codename: 'cookie_policy_bar',
          name: 'Cookie policy banner',
        },
        training___cta_buy_link: {
          codename: 'training___cta_buy_link',
          name: 'Training - CTA Buy Link',
        },
        feedback_form___no_button: {
          codename: 'feedback_form___no_button',
          name: 'Feedback form - No button',
        },
        link_to_app_tooltip: {
          codename: 'link_to_app_tooltip',
          name: 'Link to app tooltip',
        },
        sign_in_button: {
          codename: 'sign_in_button',
          name: 'Sign in button',
        },
        technology_picker_tooltip: {
          codename: 'technology_picker_tooltip',
          name: 'Technology picker tooltip',
        },
        portal_name: {
          codename: 'portal_name',
          name: 'Portal name',
        },
        toggle_breaking_changes_only: {
          codename: 'toggle_breaking_changes_only',
          name: 'Toggle breaking changes only',
        },
        article___next_steps: {
          codename: 'article___next_steps',
          name: 'Article - Next steps heading text',
        },
        video___expand: {
          codename: 'video___expand',
          name: 'Video - Expand',
        },
        sign_out_button: {
          codename: 'sign_out_button',
          name: 'Sign out button',
        },
        feedback_form___feedback_label: {
          codename: 'feedback_form___feedback_label',
          name: 'Feedback form - Feedback label',
        },
        training___free_course_label: {
          codename: 'training___free_course_label',
          name: 'Training - Free course label',
        },
        search___no_results: {
          codename: 'search___no_results',
          name: 'Search - No results',
        },
        search___404_page_results: {
          codename: 'search___404_page_results',
          name: 'Search - 404 page results',
        },
        training___cta_resume_course: {
          codename: 'training___cta_resume_course',
          name: 'Training - CTA Resume Course',
        },
        feedback_form___submit_button: {
          codename: 'feedback_form___submit_button',
          name: 'Feedback form - Submit button',
        },
        code_block___copy_code_button: {
          codename: 'code_block___copy_code_button',
          name: 'Code block - Copy code button',
        },
        heading___copy_url_active: {
          codename: 'heading___copy_url_active',
          name: 'Heading - copy URL active',
        },
        home___show_less: {
          codename: 'home___show_less',
          name: 'Home - Show less',
        },
        affected_services_selector_title: {
          codename: 'affected_services_selector_title',
          name: 'Affected services selector title',
        },
        embedded_content_dnt_notice: {
          codename: 'embedded_content_dnt_notice',
          name: 'Article - Embedded content DNT notice',
        },
        code_block___empty_state_text: {
          codename: 'code_block___empty_state_text',
          name: 'Code block - Empty state text',
        },
        training___personas_selector_title: {
          codename: 'training___personas_selector_title',
          name: 'Training - Personas selector title',
        },
        previous_part_link_text: {
          codename: 'previous_part_link_text',
          name: 'Article - Previous part link text',
        },
        feedback_form___yes_message: {
          codename: 'feedback_form___yes_message',
          name: 'Feedback form - Yes message',
        },
        home___show_more: {
          codename: 'home___show_more',
          name: 'Home - Show more',
        },
        training___download_certificate: {
          codename: 'training___download_certificate',
          name: 'Training - Download Certificate',
        },
        sign_in_error_subscription_missing_text: {
          codename: 'sign_in_error_subscription_missing_text',
          name: 'Sign in error subscription missing text',
        },
        training___cta_start_course: {
          codename: 'training___cta_start_course',
          name: 'Training - CTA Start Course',
        },
        technology_selector_label: {
          codename: 'technology_selector_label',
          name: 'Technology selector label',
        },
        feedback_form___no_message: {
          codename: 'feedback_form___no_message',
          name: 'Feedback form - No message',
        },
        video___pause: {
          codename: 'video___pause',
          name: 'Video - Pause',
        },
        feedback_form___heading: {
          codename: 'feedback_form___heading',
          name: 'Feedback form - Heading',
        },
        heading___copy_url_hover: {
          codename: 'heading___copy_url_hover',
          name: 'Heading - copy URL hover',
        },
        sign_up_button: {
          codename: 'sign_up_button',
          name: 'Sign up button',
        },
        feedback_form___email_label: {
          codename: 'feedback_form___email_label',
          name: 'Feedback form - Email label',
        },
        video___play: {
          codename: 'video___play',
          name: 'Video - Play',
        },
        form_field_validation___recaptcha_message: {
          codename: 'form_field_validation___recaptcha_message',
          name: 'Form field validation - ReCaptcha message',
        },
        article___introduction: {
          codename: 'article___introduction',
          name: 'Article - Introduction',
        },
        training___cta_coming_soon: {
          codename: 'training___cta_coming_soon',
          name: 'Training - CTA coming soon',
        },
        training___view_details: {
          codename: 'training___view_details',
          name: 'Training - View Course Details',
        },
        toggle_all_changes: {
          codename: 'toggle_all_changes',
          name: 'Toggle all changes',
        },
      },
    },
    zapi__category: {
      codename: 'zapi__category',
      name: 'zAPI ​Category',
      elements: {
        description: {
          codename: 'description',
          name: 'Description',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        path_operations: {
          codename: 'path_operations',
          name: 'Path operations',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
      },
    },
    zapi_contact: {
      codename: 'zapi_contact',
      name: 'zAPI Contact',
      elements: {
        email: {
          codename: 'email',
          name: 'Email',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
      },
    },
    zapi_discriminator: {
      codename: 'zapi_discriminator',
      name: 'zAPI Discriminator',
      elements: {
        mapping: {
          codename: 'mapping',
          name: 'Mapping',
        },
        property_name: {
          codename: 'property_name',
          name: 'Property name',
        },
      },
    },
    zapi_discriminator__map_item: {
      codename: 'zapi_discriminator__map_item',
      name: 'zAPI Discriminator: Map item',
      elements: {
        schema: {
          codename: 'schema',
          name: 'Schema',
        },
        discriminator_value: {
          codename: 'discriminator_value',
          name: 'Discriminator value',
        },
      },
    },
    zapi_license: {
      codename: 'zapi_license',
      name: 'zAPI License',
      elements: {
        name: {
          codename: 'name',
          name: 'Name',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
      },
    },
    zapi_parameter: {
      codename: 'zapi_parameter',
      name: 'zAPI Parameter',
      elements: {
        explode: {
          codename: 'explode',
          name: 'Explode',
        },
        example: {
          codename: 'example',
          name: 'Example',
        },
        deprecated: {
          codename: 'deprecated',
          name: 'Deprecated',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        location: {
          codename: 'location',
          name: 'Location',
        },
        schema: {
          codename: 'schema',
          name: 'Schema',
        },
        style: {
          codename: 'style',
          name: 'Style',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
        required: {
          codename: 'required',
          name: 'Required',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
      },
    },
    zapi_path_operation: {
      codename: 'zapi_path_operation',
      name: 'zAPI Path operation',
      elements: {
        description: {
          codename: 'description',
          name: 'Description',
        },
        code_samples: {
          codename: 'code_samples',
          name: 'Code samples',
        },
        path: {
          codename: 'path',
          name: 'Path',
        },
        request_body: {
          codename: 'request_body',
          name: 'Request body',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        responses: {
          codename: 'responses',
          name: 'Responses',
        },
        path_operation: {
          codename: 'path_operation',
          name: 'Path operation',
        },
        deprecated: {
          codename: 'deprecated',
          name: 'Deprecated',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
        name: {
          codename: 'name',
          name: 'Title',
        },
        parameters: {
          codename: 'parameters',
          name: 'Parameters',
        },
      },
    },
    zapi_property_referencing_a_schema: {
      codename: 'zapi_property_referencing_a_schema',
      name: 'zAPI Property with an existing schema',
      elements: {
        schema: {
          codename: 'schema',
          name: 'Schema',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
      },
    },
    zapi_request_body: {
      codename: 'zapi_request_body',
      name: 'zAPI Request body',
      elements: {
        required: {
          codename: 'required',
          name: 'Required',
        },
        schema: {
          codename: 'schema',
          name: 'Schema',
        },
        example: {
          codename: 'example',
          name: 'Example',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        media_type: {
          codename: 'media_type',
          name: 'Media type',
        },
      },
    },
    zapi_response: {
      codename: 'zapi_response',
      name: 'zAPI Response',
      elements: {
        description: {
          codename: 'description',
          name: 'Description',
        },
        headers: {
          codename: 'headers',
          name: 'Headers',
        },
        schema: {
          codename: 'schema',
          name: 'Schema',
        },
        example: {
          codename: 'example',
          name: 'Example',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        media_type: {
          codename: 'media_type',
          name: 'Media type',
        },
        http_status: {
          codename: 'http_status',
          name: 'HTTP status',
        },
      },
    },
    zapi_schema__allof: {
      codename: 'zapi_schema__allof',
      name: 'zAPI Schema: AllOf',
      elements: {
        common_schema_object_property_elements__writeonly: {
          codename: 'common_schema_object_property_elements__writeonly',
          name: 'Write only (shown in request body)',
        },
        common_schema_object_property_elements__deprecated: {
          codename: 'common_schema_object_property_elements__deprecated',
          name: 'Deprecated',
        },
        schemas: {
          codename: 'schemas',
          name: 'Schemas',
        },
        common_schema_object_property_elements__readonly: {
          codename: 'common_schema_object_property_elements__readonly',
          name: 'Read only (shown in response)',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        common_schema_object_property_elements__nullable: {
          codename: 'common_schema_object_property_elements__nullable',
          name: 'Nullable',
        },
      },
    },
    zapi_schema__anyof: {
      codename: 'zapi_schema__anyof',
      name: 'zAPI Schema: AnyOf',
      elements: {
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        common_schema_object_property_elements__writeonly: {
          codename: 'common_schema_object_property_elements__writeonly',
          name: 'Write only (shown in request body)',
        },
        common_schema_object_property_elements__deprecated: {
          codename: 'common_schema_object_property_elements__deprecated',
          name: 'Deprecated',
        },
        schemas: {
          codename: 'schemas',
          name: 'Schemas',
        },
        common_schema_object_property_elements__readonly: {
          codename: 'common_schema_object_property_elements__readonly',
          name: 'Read only (shown in response)',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        common_schema_object_property_elements__nullable: {
          codename: 'common_schema_object_property_elements__nullable',
          name: 'Nullable',
        },
      },
    },
    zapi_schema__array: {
      codename: 'zapi_schema__array',
      name: 'zAPI Schema: Array',
      elements: {
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        items: {
          codename: 'items',
          name: 'Items',
        },
        maxitems: {
          codename: 'maxitems',
          name: 'Maximum number of items',
        },
        common_schema_object_property_elements__writeonly: {
          codename: 'common_schema_object_property_elements__writeonly',
          name: 'Write only (shown in request body)',
        },
        common_schema_object_property_elements__deprecated: {
          codename: 'common_schema_object_property_elements__deprecated',
          name: 'Deprecated',
        },
        uniqueitems: {
          codename: 'uniqueitems',
          name: 'Array contains unique items',
        },
        common_schema_object_property_elements__readonly: {
          codename: 'common_schema_object_property_elements__readonly',
          name: 'Read only (shown in response)',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        minitems: {
          codename: 'minitems',
          name: 'Minimum number of items',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        common_schema_object_property_elements__nullable: {
          codename: 'common_schema_object_property_elements__nullable',
          name: 'Nullable',
        },
      },
    },
    zapi_schema__boolean: {
      codename: 'zapi_schema__boolean',
      name: 'zAPI Schema: Boolean',
      elements: {
        common_schema_object_property_elements__writeonly: {
          codename: 'common_schema_object_property_elements__writeonly',
          name: 'Write only (shown in request body)',
        },
        common_schema_object_property_elements__deprecated: {
          codename: 'common_schema_object_property_elements__deprecated',
          name: 'Deprecated',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        common_schema_object_property_elements__readonly: {
          codename: 'common_schema_object_property_elements__readonly',
          name: 'Read only (shown in response)',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        common_schema_object_property_elements__nullable: {
          codename: 'common_schema_object_property_elements__nullable',
          name: 'Nullable',
        },
      },
    },
    zapi_schema__integer: {
      codename: 'zapi_schema__integer',
      name: 'zAPI Schema: Integer',
      elements: {
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        common_schema_object_property_elements__writeonly: {
          codename: 'common_schema_object_property_elements__writeonly',
          name: 'Write only (shown in request body)',
        },
        common_schema_object_property_elements__deprecated: {
          codename: 'common_schema_object_property_elements__deprecated',
          name: 'Deprecated',
        },
        maximum: {
          codename: 'maximum',
          name: 'Maximum',
        },
        minimum: {
          codename: 'minimum',
          name: 'Minimum',
        },
        format: {
          codename: 'format',
          name: 'Format',
        },
        accepted_values: {
          codename: 'accepted_values',
          name: 'Accepted values',
        },
        common_schema_object_property_elements__readonly: {
          codename: 'common_schema_object_property_elements__readonly',
          name: 'Read only (shown in response)',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        common_schema_object_property_elements__nullable: {
          codename: 'common_schema_object_property_elements__nullable',
          name: 'Nullable',
        },
        default_value: {
          codename: 'default_value',
          name: 'Default value',
        },
      },
    },
    zapi_schema__number: {
      codename: 'zapi_schema__number',
      name: 'zAPI Schema: Number',
      elements: {
        minimum: {
          codename: 'minimum',
          name: 'Minimum value',
        },
        common_schema_object_property_elements__writeonly: {
          codename: 'common_schema_object_property_elements__writeonly',
          name: 'Write only (shown in request body)',
        },
        common_schema_object_property_elements__deprecated: {
          codename: 'common_schema_object_property_elements__deprecated',
          name: 'Deprecated',
        },
        maximum: {
          codename: 'maximum',
          name: 'Maximum value',
        },
        accepted_values: {
          codename: 'accepted_values',
          name: 'Accepted values',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        common_schema_object_property_elements__readonly: {
          codename: 'common_schema_object_property_elements__readonly',
          name: 'Read only (shown in response)',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        format: {
          codename: 'format',
          name: 'Format',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        common_schema_object_property_elements__nullable: {
          codename: 'common_schema_object_property_elements__nullable',
          name: 'Nullable',
        },
      },
    },
    zapi_schema__object: {
      codename: 'zapi_schema__object',
      name: 'zAPI Schema: Object',
      elements: {
        required: {
          codename: 'required',
          name: 'Required properties',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        additional_properties_name: {
          codename: 'additional_properties_name',
          name: 'Additional properties name',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        properties: {
          codename: 'properties',
          name: 'Properties',
        },
        additional_properties: {
          codename: 'additional_properties',
          name: 'Additional properties',
        },
      },
    },
    zapi_schema__oneof: {
      codename: 'zapi_schema__oneof',
      name: 'zAPI Schema: OneOf',
      elements: {
        discriminator: {
          codename: 'discriminator',
          name: 'Mapping rules',
        },
        common_schema_object_property_elements__writeonly: {
          codename: 'common_schema_object_property_elements__writeonly',
          name: 'Write only (shown in request body)',
        },
        common_schema_object_property_elements__deprecated: {
          codename: 'common_schema_object_property_elements__deprecated',
          name: 'Deprecated',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        common_schema_object_property_elements__readonly: {
          codename: 'common_schema_object_property_elements__readonly',
          name: 'Read only (shown in response)',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        schemas: {
          codename: 'schemas',
          name: 'Schemas',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        common_schema_object_property_elements__nullable: {
          codename: 'common_schema_object_property_elements__nullable',
          name: 'Nullable',
        },
      },
    },
    zapi_schema__string: {
      codename: 'zapi_schema__string',
      name: 'zAPI Schema: String',
      elements: {
        format: {
          codename: 'format',
          name: 'Format',
        },
        accepted_values: {
          codename: 'accepted_values',
          name: 'Accepted values',
        },
        common_schema_object_property_elements__writeonly: {
          codename: 'common_schema_object_property_elements__writeonly',
          name: 'Write only (shown in request body)',
        },
        common_schema_object_property_elements__deprecated: {
          codename: 'common_schema_object_property_elements__deprecated',
          name: 'Deprecated',
        },
        minlength: {
          codename: 'minlength',
          name: 'Minimum length',
        },
        default_value: {
          codename: 'default_value',
          name: 'Default value',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        common_schema_object_property_elements__readonly: {
          codename: 'common_schema_object_property_elements__readonly',
          name: 'Read only (shown in response)',
        },
        common_schema_elements__example: {
          codename: 'common_schema_elements__example',
          name: 'Example',
        },
        common_schema_elements__description: {
          codename: 'common_schema_elements__description',
          name: 'Description',
        },
        maxlength: {
          codename: 'maxlength',
          name: 'Maximum length',
        },
        common_schema_elements__name: {
          codename: 'common_schema_elements__name',
          name: 'Name',
        },
        common_schema_object_property_elements__nullable: {
          codename: 'common_schema_object_property_elements__nullable',
          name: 'Nullable',
        },
      },
    },
    zapi_security_scheme: {
      codename: 'zapi_security_scheme',
      name: 'zAPI Security scheme',
      elements: {
        bearer_format: {
          codename: 'bearer_format',
          name: 'Bearer format',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        api_key_name: {
          codename: 'api_key_name',
          name: 'API key name',
        },
        name: {
          codename: 'name',
          name: 'Name',
        },
        scheme: {
          codename: 'scheme',
          name: 'Scheme',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        type: {
          codename: 'type',
          name: 'Type',
        },
        api_key_location: {
          codename: 'api_key_location',
          name: 'API key location',
        },
      },
    },
    zapi_server: {
      codename: 'zapi_server',
      name: 'zAPI Server',
      elements: {
        description: {
          codename: 'description',
          name: 'Description',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
      },
    },
    zapi_specification: {
      codename: 'zapi_specification',
      name: 'zAPI Specification',
      elements: {
        description: {
          codename: 'description',
          name: 'Description',
        },
        url: {
          codename: 'url',
          name: 'URL',
        },
        redirect_urls: {
          codename: 'redirect_urls',
          name: 'Redirect URLs',
        },
        api_reference: {
          codename: 'api_reference',
          name: 'API reference',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        license: {
          codename: 'license',
          name: 'License information',
        },
        categories: {
          codename: 'categories',
          name: 'Categories',
        },
        servers: {
          codename: 'servers',
          name: 'Base URLs',
        },
        terms_of_service: {
          codename: 'terms_of_service',
          name: 'Terms of service',
        },
        version: {
          codename: 'version',
          name: 'Version',
        },
        security: {
          codename: 'security',
          name: 'Authentication',
        },
        contact: {
          codename: 'contact',
          name: 'Contact information',
        },
        api_status: {
          codename: 'api_status',
          name: 'Is this API in beta?',
        },
      },
    },
  },
  taxonomies: {
    api_reference: {
      codename: 'api_reference',
      name: 'API reference',
      terms: {
        content_management_api_v1: {
          codename: 'content_management_api_v1',
          name: 'Management API v1',
          terms: {},
        },
        content_management_api_v2: {
          codename: 'content_management_api_v2',
          name: 'Management API v2',
          terms: {},
        },
        delivery_api: {
          codename: 'delivery_api',
          name: 'Delivery API',
          terms: {},
        },
        recommendation_api: {
          codename: 'recommendation_api',
          name: 'Recommendations API (deprecated)',
          terms: {},
        },
        recommendations_api_v2: {
          codename: 'recommendations_api_v2',
          name: 'Smart Recommendations API',
          terms: {},
        },
      },
    },
    custom_css_class: {
      codename: 'custom_css_class',
      name: 'Training custom class',
      terms: {
        show_as_tip: {
          codename: 'show_as_tip',
          name: 'Show as tip',
          terms: {},
        },
        show_as_warning: {
          codename: 'show_as_warning',
          name: 'Show as warning',
          terms: {},
        },
        show_as_info: {
          codename: 'show_as_info',
          name: 'Show as info',
          terms: {},
        },
        show_as_key_points: {
          codename: 'show_as_key_points',
          name: 'Show as key points',
          terms: {},
        },
      },
    },
    path_operation: {
      codename: 'path_operation',
      name: 'Path operation',
      terms: {
        get: {
          codename: 'get',
          name: 'GET',
          terms: {},
        },
        post: {
          codename: 'post',
          name: 'POST',
          terms: {},
        },
        put: {
          codename: 'put',
          name: 'PUT',
          terms: {},
        },
        patch: {
          codename: 'patch',
          name: 'PATCH',
          terms: {},
        },
        delete: {
          codename: 'delete',
          name: 'DELETE',
          terms: {},
        },
      },
    },
    platform: {
      codename: 'platform',
      name: 'Technology',
      terms: {
        rest: {
          codename: 'rest',
          name: 'REST',
          terms: {},
        },
        _net: {
          codename: '_net',
          name: '.NET',
          terms: {},
        },
        javascript: {
          codename: 'javascript',
          name: 'JavaScript',
          terms: {},
        },
        typescript: {
          codename: 'typescript',
          name: 'TypeScript',
          terms: {},
        },
        java: {
          codename: 'java',
          name: 'Java',
          terms: {},
        },
        android: {
          codename: 'android',
          name: 'Android',
          terms: {},
        },
        ios: {
          codename: 'ios',
          name: 'iOS',
          terms: {},
        },
        php: {
          codename: 'php',
          name: 'PHP',
          terms: {},
        },
        ruby: {
          codename: 'ruby',
          name: 'Ruby',
          terms: {},
        },
        react: {
          codename: 'react',
          name: 'React',
          terms: {},
        },
        vue_js: {
          codename: 'vue_js',
          name: 'Vue.js',
          terms: {},
        },
        graphql: {
          codename: 'graphql',
          name: 'GraphQL',
          terms: {},
        },
      },
    },
    programming_language: {
      codename: 'programming_language',
      name: 'Programming language',
      terms: {
        c_: {
          codename: 'c_',
          name: 'C#',
          terms: {},
        },
        css: {
          codename: 'css',
          name: 'CSS',
          terms: {},
        },
        curl: {
          codename: 'curl',
          name: 'cURL',
          terms: {},
        },
        graphql: {
          codename: 'graphql',
          name: 'GraphQL',
          terms: {},
        },
        html: {
          codename: 'html',
          name: 'HTML',
          terms: {},
        },
        http: {
          codename: 'http',
          name: 'HTTP',
          terms: {},
        },
        java: {
          codename: 'java',
          name: 'Java',
          terms: {},
        },
        javascript: {
          codename: 'javascript',
          name: 'JavaScript',
          terms: {},
        },
        json: {
          codename: 'json',
          name: 'JSON',
          terms: {},
        },
        php: {
          codename: 'php',
          name: 'PHP',
          terms: {},
        },
        python: {
          codename: 'python',
          name: 'Python',
          terms: {},
        },
        ruby: {
          codename: 'ruby',
          name: 'Ruby',
          terms: {},
        },
        shell: {
          codename: 'shell',
          name: 'shell',
          terms: {},
        },
        swift: {
          codename: 'swift',
          name: 'Swift',
          terms: {},
        },
        typescript: {
          codename: 'typescript',
          name: 'TypeScript',
          terms: {},
        },
        xml: {
          codename: 'xml',
          name: 'XML',
          terms: {},
        },
      },
    },
    training_course: {
      codename: 'training_course',
      name: 'Training course',
      terms: {
        k01: {
          codename: 'k01',
          name: 'k01 - Headless CMS 101',
          terms: {},
        },
        k02: {
          codename: 'k02',
          name: 'k02 - Hello Kontent',
          terms: {},
        },
        k03: {
          codename: 'k03',
          name: 'k03 - Authoring in Kontent',
          terms: {},
        },
        m02: {
          codename: 'm02',
          name: 'm02 - Advanced Content Modeling',
          terms: {},
        },
        p01: {
          codename: 'p01',
          name: 'p01 - Content Strategy for Partners',
          terms: {},
        },
        w01: {
          codename: 'w01',
          name: 'w01 - Get Started with Taxonomy',
          terms: {},
        },
        w02: {
          codename: 'w02',
          name: 'w02 - Get Started with Modular Content',
          terms: {},
        },
        w03: {
          codename: 'w03',
          name: 'w03 - Headless CMS 102 - Digital Transformation and Microservice Architecture',
          terms: {},
        },
        w04: {
          codename: 'w04',
          name: 'w04 - Headless CMS 103 - Digital and Content Maturity',
          terms: {},
        },
        w05: {
          codename: 'w05',
          name: '(Obsolete) w05 - Headless CMS 104 - Content Recommendation and Personalization',
          terms: {},
        },
        certifications: {
          codename: 'certifications',
          name: 'Certifications',
          terms: {},
        },
        t01___how_to_eat_sushi: {
          codename: 't01___how_to_eat_sushi',
          name: 't01 - How to eat Sushi',
          terms: {},
        },
      },
    },
    visibility: {
      codename: 'visibility',
      name: 'Visibility',
      terms: {
        excluded_from_search: {
          codename: 'excluded_from_search',
          name: 'Exclude from search',
          terms: {},
        },
        excluded_from_navigation: {
          codename: 'excluded_from_navigation',
          name: 'Exclude from navigation',
          terms: {},
        },
      },
    },
  },
};
