import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-5'
 */
export type TrainingHotGraphic = IContentItem<{
  pins: Elements.RichTextElement;
  adapt_component_title__title: Elements.TextElement;
  adapt_progress_settings__adjust_progress_settings: Elements.MultipleChoiceElement;
  content: Elements.RichTextElement;
  graphic: Elements.AssetsElement;
  pin_preview: Elements.CustomElement;
  displayoptions__css_classes: Elements.TaxonomyElement;
  use_numbered_pins: Elements.MultipleChoiceElement;
  displayoptions__layout: Elements.MultipleChoiceElement;
}>;
