import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0-5'
 */
export type TrainingHotGraphicPin = IContentItem<{
  top: Elements.NumberElement;
  image: Elements.AssetsElement;
  title: Elements.TextElement;
  body: Elements.RichTextElement;
  left: Elements.NumberElement;
}>;
